spring:
  datasource:
    initial-size: 5
    max-active: 10
    max-idle: 2
    max-lifetime: 9000
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
    connection-timeout: 900
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  view:
    suffix: jsp
    prefix: WEB-INF/jsp
