/*
SQLyog Ultimate v12.09 (32 bit)
MySQL - 5.6.25 : Database - GOLD_BOSS_SYS
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`GOLD_BOSS_SYS` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `GOLD_BOSS_SYS`;

/*Table structure for table `GB_SYS_CITY` */

CREATE TABLE `GB_SYS_CITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATE_ID` bigint(20) NOT NULL,
  `CITY_CODE` varchar(40) NOT NULL,
  `CITY_NAME` varchar(120) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_CITY` */

LOCK TABLES `GB_SYS_CITY` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_COUNTRY` */

CREATE TABLE `GB_SYS_COUNTRY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CNT_CODE` varchar(40) NOT NULL,
  `CNT_NAME` varchar(120) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_COUNTRY` */

LOCK TABLES `GB_SYS_COUNTRY` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_DICT` */

CREATE TABLE `GB_SYS_DICT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DICT_TYPE` varchar(40) NOT NULL,
  `DICT_NAME` varchar(80) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_DICT` */

LOCK TABLES `GB_SYS_DICT` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_DICT_DETAIL` */

CREATE TABLE `GB_SYS_DICT_DETAIL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DICT_TYPE_ID` bigint(20) NOT NULL,
  `DICT_VALUE` varchar(40) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_DICT_ID` (`DICT_TYPE_ID`),
  CONSTRAINT `FK_DICT_ID` FOREIGN KEY (`DICT_TYPE_ID`) REFERENCES `GB_SYS_DICT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_DICT_DETAIL` */

LOCK TABLES `GB_SYS_DICT_DETAIL` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_DISTRICT` */

CREATE TABLE `GB_SYS_DISTRICT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CITY_ID` bigint(20) NOT NULL,
  `DST_CODE` varchar(40) NOT NULL,
  `DST_NAME` varchar(200) NOT NULL,
  `DST_DESC` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_DISTRICT` */

LOCK TABLES `GB_SYS_DISTRICT` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_PERMISSION` */

CREATE TABLE `GB_SYS_PERMISSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PMS_NAME` varchar(80) NOT NULL,
  `PMS_CODE` varchar(40) NOT NULL,
  `PMS_DESC` text,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `LEVEL` int(3) NOT NULL,
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FK_PMS_SELF_ID` (`PARENT_ID`),
  CONSTRAINT `FK_PMS_SELF_ID` FOREIGN KEY (`PARENT_ID`) REFERENCES `GB_SYS_PERMISSION` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_PERMISSION` */

LOCK TABLES `GB_SYS_PERMISSION` WRITE;

insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (1,'权限顶级','ROOT','ROOT',NULL,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (2,'权限2级','NODE2','权限',1,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (3,'权限2级','NODE2','权限',1,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (4,'权限3级','NODE3','权限',2,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (5,'权限3级','NODE3','权限',3,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (6,'权限3级','NODE3','权限',3,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (7,'权限3级','NODE3','权限',3,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (8,'权限4级','NODE4','权限',4,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (9,'权限4级','NODE4','权限',4,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (10,'权限4级','NODE4','权限',5,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (11,'权限4级','NODE4','权限',6,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (12,'权限4级','NODE4','权限',7,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (13,'权限4级','NODE4','权限',7,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (14,'权限4级','NODE4','权限',7,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (15,'权限4级','NODE4','权限',7,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');
insert  into `GB_SYS_PERMISSION`(`ID`,`PMS_NAME`,`PMS_CODE`,`PMS_DESC`,`PARENT_ID`,`LEVEL`,`CREATE_TIME`,`UPDATE_TIME`) values (16,'权限5级','NODE5','权限',8,0,'2015-12-17 10:44:27','2015-12-17 10:44:27');

UNLOCK TABLES;

/*Table structure for table `GB_SYS_ROLE` */

CREATE TABLE `GB_SYS_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(80) NOT NULL,
  `ROLE_CODE` varchar(40) NOT NULL,
  `ROLE_DESC` text,
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_ROLE` */

LOCK TABLES `GB_SYS_ROLE` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_ROLE_PMS` */

CREATE TABLE `GB_SYS_ROLE_PMS` (
  `ROLE_ID` bigint(20) NOT NULL,
  `PMS_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`PMS_ID`),
  KEY `FK_PPM_PMS_ID` (`PMS_ID`),
  CONSTRAINT `FK_PPM_PMS_ID` FOREIGN KEY (`PMS_ID`) REFERENCES `GB_SYS_PERMISSION` (`ID`),
  CONSTRAINT `FK_PPM_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `GB_SYS_ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_ROLE_PMS` */

LOCK TABLES `GB_SYS_ROLE_PMS` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_SOCKET_HISTORY` */

CREATE TABLE `GB_SYS_SOCKET_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL,
  `CONTENTS` longtext,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DEL_MARKER` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_SOCKET_HISTORY` */

LOCK TABLES `GB_SYS_SOCKET_HISTORY` WRITE;

insert  into `GB_SYS_SOCKET_HISTORY`(`ID`,`USER_ID`,`CONTENTS`,`CREATE_TIME`,`DEL_MARKER`) values (1,1,'Hello!WebSocket!','1974-08-11 23:59:24',0);
insert  into `GB_SYS_SOCKET_HISTORY`(`ID`,`USER_ID`,`CONTENTS`,`CREATE_TIME`,`DEL_MARKER`) values (2,1,'Hello!WebSocket!我要中文','2016-02-05 23:54:04',0);
insert  into `GB_SYS_SOCKET_HISTORY`(`ID`,`USER_ID`,`CONTENTS`,`CREATE_TIME`,`DEL_MARKER`) values (3,1,'Hello!WebSocket!我要中文','2016-02-05 23:54:03',0);
insert  into `GB_SYS_SOCKET_HISTORY`(`ID`,`USER_ID`,`CONTENTS`,`CREATE_TIME`,`DEL_MARKER`) values (4,1,'明天我要嫁给你吗?','2016-02-05 23:54:03',0);

UNLOCK TABLES;

/*Table structure for table `GB_SYS_STATE` */

CREATE TABLE `GB_SYS_STATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CNT_ID` bigint(20) NOT NULL,
  `STATE_CODE` varchar(40) NOT NULL,
  `STATE_NAME` varchar(120) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_STATE` */

LOCK TABLES `GB_SYS_STATE` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_USER` */

CREATE TABLE `GB_SYS_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACCOUNT` varchar(40) NOT NULL,
  `PASSWD` varchar(90) DEFAULT NULL,
  `DELETE_FLAG` int(1) DEFAULT NULL,
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_USER` */

LOCK TABLES `GB_SYS_USER` WRITE;

UNLOCK TABLES;

/*Table structure for table `GB_SYS_USER_ROLE` */

CREATE TABLE `GB_SYS_USER_ROLE` (
  `USER_ID` bigint(20) NOT NULL,
  `ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `FK_URM_ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `FK_URM_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `GB_SYS_ROLE` (`ID`),
  CONSTRAINT `FK_URM_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `GB_SYS_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `GB_SYS_USER_ROLE` */

LOCK TABLES `GB_SYS_USER_ROLE` WRITE;

UNLOCK TABLES;

/* Function  structure for function  `GetChildren` */

DELIMITER $$

/*!50003 CREATE DEFINER=`root`@`::1` FUNCTION `GetChildren`(rootId int) RETURNS varchar(1000) CHARSET utf8
BEGIN
	DECLARE sTemp VARCHAR(1000);
	DECLARE sTempChd VARCHAR(1000);
	SET sTemp = '$';
	SET sTempChd =cast(rootId as CHAR);
	WHILE sTempChd is not null DO
		SET sTemp = concat(sTemp,',',sTempChd);
		SELECT group_concat(id) INTO sTempChd FROM GB_SYS_PERMISSION where FIND_IN_SET(PARENT_ID,sTempChd)>0;
	END WHILE;
	RETURN sTemp;
    END */$$
DELIMITER ;

/* Function  structure for function  `GetParents` */

DELIMITER $$

/*!50003 CREATE DEFINER=`root`@`::1` FUNCTION `GetParents`(parentId int) RETURNS varchar(10000) CHARSET utf8
BEGIN
	DECLARE sTemp VARCHAR(1000);
	DECLARE sTempFather VARCHAR(1000);
	SET sTemp = '$';
	SET sTempFather =CAST(parentId AS CHAR);
	WHILE sTempFather IS NOT NULL DO
		SET sTemp = CONCAT(sTemp,',',sTempFather);
		SELECT GROUP_CONCAT(PARENT_ID) INTO sTempFather FROM GB_SYS_PERMISSION WHERE FIND_IN_SET(ID,sTempFather)>0;
	END WHILE;
	RETURN sTemp;
    END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
